-- MySQL Script generated by MySQL Workbench
-- Sun Aug  1 23:48:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_factory_sergio_marchio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_factory_sergio_marchio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_factory_sergio_marchio` DEFAULT CHARACTER SET utf8 ;
USE `car_factory_sergio_marchio` ;

-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`car_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`car_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  `fuel_type` VARCHAR(45) NOT NULL,
  `unitary_price` DOUBLE NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_car_models_brands1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_car_models_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `car_factory_sergio_marchio`.`brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_cities_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_cities_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `car_factory_sergio_marchio`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `dept_number` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_addresses_cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_addresses_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `car_factory_sergio_marchio`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_clients_addresses1_idx` (`address_id` ASC),
  CONSTRAINT `fk_clients_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `car_factory_sergio_marchio`.`addresses` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`client_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`client_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NOT NULL,
  `discount_percent` DOUBLE NULL,
  `delivery_date` DATETIME NULL,
  `client_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_clients1_idx` (`client_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `car_factory_sergio_marchio`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_providers_addresses1_idx` (`address_id` ASC),
  CONSTRAINT `fk_providers_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `car_factory_sergio_marchio`.`addresses` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`paint_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`paint_colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `provider_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_paint_colors_providers1_idx` (`provider_id` ASC),
  CONSTRAINT `fk_paint_colors_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `car_factory_sergio_marchio`.`providers` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufactured_date` DATETIME NULL,
  `car_model_id` INT NOT NULL,
  `client_order_id` INT NULL,
  `paint_color_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_cars_car_models_idx` (`car_model_id` ASC),
  INDEX `fk_cars_orders1_idx` (`client_order_id` ASC),
  INDEX `fk_cars_paint_colors1_idx` (`paint_color_id` ASC),
  CONSTRAINT `fk_cars_car_models`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `car_factory_sergio_marchio`.`car_models` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_cars_orders1`
    FOREIGN KEY (`client_order_id`)
    REFERENCES `car_factory_sergio_marchio`.`client_orders` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_cars_paint_colors1`
    FOREIGN KEY (`paint_color_id`)
    REFERENCES `car_factory_sergio_marchio`.`paint_colors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`part_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`part_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_part_types_providers1_idx` (`provider_id` ASC),
  CONSTRAINT `fk_part_types_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `car_factory_sergio_marchio`.`providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`model_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`model_colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paint_color_id` INT NOT NULL,
  `car_model_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paint_colors_has_car_models_car_models1_idx` (`car_model_id` ASC),
  INDEX `fk_paint_colors_has_car_models_paint_colors1_idx` (`paint_color_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_paint_colors_has_car_models_paint_colors1`
    FOREIGN KEY (`paint_color_id`)
    REFERENCES `car_factory_sergio_marchio`.`paint_colors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_paint_colors_has_car_models_car_models1`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `car_factory_sergio_marchio`.`car_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serial_number` VARCHAR(45) NOT NULL,
  `car_id` INT NOT NULL,
  `part_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_parts_cars1_idx` (`car_id` ASC),
  INDEX `fk_parts_part_types1_idx` (`part_type_id` ASC),
  CONSTRAINT `fk_parts_cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `car_factory_sergio_marchio`.`cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parts_part_types1`
    FOREIGN KEY (`part_type_id`)
    REFERENCES `car_factory_sergio_marchio`.`part_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`model_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`model_parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `car_model_id` INT NOT NULL,
  `part_type_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_part_types_has_car_models_car_models1_idx` (`car_model_id` ASC),
  INDEX `fk_part_types_has_car_models_part_types1_idx` (`part_type_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_part_types_has_car_models_part_types1`
    FOREIGN KEY (`part_type_id`)
    REFERENCES `car_factory_sergio_marchio`.`part_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_part_types_has_car_models_car_models1`
    FOREIGN KEY (`car_model_id`)
    REFERENCES `car_factory_sergio_marchio`.`car_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `head_employee_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_departments_employees1_idx` (`head_employee_id` ASC),
  CONSTRAINT `fk_departments_employees1`
    FOREIGN KEY (`head_employee_id`)
    REFERENCES `car_factory_sergio_marchio`.`employees` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `shift` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NOT NULL,
  `address_id` INT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_employees_addresses1_idx` (`address_id` ASC),
  INDEX `fk_employees_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employees_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `car_factory_sergio_marchio`.`addresses` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `car_factory_sergio_marchio`.`departments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`assembly_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`assembly_lines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`assembly_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`assembly_employees` (
  `employee_id` INT NOT NULL,
  `assembly_line_id` INT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employees_id_UNIQUE` (`employee_id` ASC),
  INDEX `fk_assembly_employees_assembly_lines1_idx` (`assembly_line_id` ASC),
  CONSTRAINT `fk_assembly_employees_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `car_factory_sergio_marchio`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assembly_employees_assembly_lines1`
    FOREIGN KEY (`assembly_line_id`)
    REFERENCES `car_factory_sergio_marchio`.`assembly_lines` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_factory_sergio_marchio`.`car_assembly_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_factory_sergio_marchio`.`car_assembly_lines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assembly_line_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  INDEX `fk_assembly_lines_has_cars_cars1_idx` (`car_id` ASC),
  INDEX `fk_assembly_lines_has_cars_assembly_lines1_idx` (`assembly_line_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_assembly_lines_has_cars_assembly_lines1`
    FOREIGN KEY (`assembly_line_id`)
    REFERENCES `car_factory_sergio_marchio`.`assembly_lines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assembly_lines_has_cars_cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `car_factory_sergio_marchio`.`cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
